name: Debaser CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Unit testing [Swift]

    runs-on: macos-11

    strategy:
      matrix:
        run-config:
          - { scheme: "DebaserTests", destination: "platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro" }
          - { scheme: "DebaserUITests", destination: "platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro" }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: set -o pipefail && xcodebuild clean test -scheme "${{ matrix.run-config['scheme'] }}" -destination "${{ matrix.run-config['destination'] }}" -showBuildTimingSummary | xcpretty

